version: '3.8'

services:
  # ==============================================================================
  # FastAPI Application Service
  # ==============================================================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ml-inference-app
    environment:
      - MODEL_NAME=t5-small
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    expose:
      - "8000"
    networks:
      - ml-network
    restart: unless-stopped
    volumes:
      # Optional: Mount logs directory for log persistence
      - ./logs:/app/logs
    command: >
      python -m uvicorn main:app 
      --host 0.0.0.0 
      --port 8000 
      --workers 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ==============================================================================
  # Nginx Reverse Proxy Service  
  # ==============================================================================
  nginx:
    image: nginx:1.24-alpine
    container_name: ml-inference-nginx
    ports:
      # Map host port 80 to container port 80
      - "80:80"
      # Optional: HTTPS port for future SSL setup
      - "443:443"
    volumes:
      # Mount our custom nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Optional: Mount logs for debugging
      - ./logs/nginx:/var/log/nginx
    networks:
      - ml-network
    restart: unless-stopped
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# ==============================================================================
# Network Configuration
# ==============================================================================
networks:
  ml-network:
    driver: bridge
    name: ml-inference-network

# ==============================================================================
# Volume Configuration (Optional)
# ==============================================================================
volumes:
  # Persistent storage for logs
  logs:
    driver: local